/-
Copyright (c) 2026 Uku Raudvere. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Uku Raudvere
-/
import Coeff2.Walks

/-!
# The HPV accounting: active loops, the statistics p, c, v, and the excess statistics
(paper §3)

Formalization choices:
* The active-loop convention `H_t` is a total function of the (0-based) time `t`, with
  junk values past the end of the walk.
* `c` uses the paper's exact positional convention: a cyclic class is completed if every
  permutation in the class occurs among `π₁,…,π_{m−1}`, i.e. strictly before the final
  position — membership in `verts.dropLast`.
* All counts are `Set.ncard`s.
* The excess statistics `e, r, ℓ` and the per-edge increments/defects are `ℤ`-valued, to
  avoid truncated subtraction; the paper's nonnegativity assertions become statements.
-/

namespace Coeff2

open List

variable {n : ℕ}

namespace Walk

/-- Paper §3, the active-loop convention: `H₁ = L(π₁)`, and `H_t = L(π_t)` if the edge
into `π_t` has weight `≥ 2` (a nonrotation edge activates the marked loop generated by
its landing vertex), while a weight-1 rotation keeps the active marked loop. -/
noncomputable def activeLoop (W : Walk n) : ℕ → MarkedLoop
  | 0 => genLoop (W.vert 0)
  | t + 1 =>
    if 2 ≤ wt n (W.vert t) (W.vert (t + 1)) then genLoop (W.vert (t + 1))
    else activeLoop W t

/-- Paper §3: a marked 2-loop is *entered* if it occurs among the `H_t`. -/
def Entered (W : Walk n) (L : MarkedLoop) : Prop :=
  ∃ t < W.numVerts, W.activeLoop t = L

/-- Paper §3: a cyclic class is *completed* (before the final vertex) if every
permutation in the class occurs among `π₁,…,π_{m−1}`, i.e. strictly before the final
position.  (This positional convention is load-bearing.) -/
def Completed (W : Walk n) (O : RotClass) : Prop :=
  ∀ w, rotClass w = O → w ∈ W.verts.dropLast

/-- Paper §3: `p(W)`, the number of distinct permutations visited by `W`. -/
noncomputable def pStat (W : Walk n) : ℕ := {w | w ∈ W.verts}.ncard

/-- Paper §3: `c(W)`, the number of cyclic classes completed before the final vertex
of `W`. -/
noncomputable def cStat (W : Walk n) : ℕ := {O | W.Completed O}.ncard

/-- Paper §3: `v(W)`, the number of marked 2-loops entered by `W`. -/
noncomputable def vStat (W : Walk n) : ℕ := {L | W.Entered L}.ncard

/-- Paper §3: the weight defect `e(W) = wt(W) + 2 − (p(W) + c(W) + v(W))`. -/
noncomputable def eStat (W : Walk n) : ℤ :=
  (W.wtW : ℤ) + 2 - (W.pStat + W.cStat + W.vStat)

/-- Paper §3: the cyclic-class surplus `r(W) = c(W) − ((n−1)! − 1)`. -/
noncomputable def rStat (W : Walk n) : ℤ :=
  (W.cStat : ℤ) - (((n - 1).factorial : ℤ) - 1)

/-- Paper §3: the marked-2-loop surplus `ℓ(W) = v(W) − (n−2)!`. -/
noncomputable def ellStat (W : Walk n) : ℤ :=
  (W.vStat : ℤ) - ((n - 2).factorial : ℤ)

/-- The increment `Δp_i` of `p` across the edge `π_{i+1} → π_{i+2}` (0-based edge `i`,
from `vert i` to `vert (i+1)`): the difference of `p` between the prefix walks through
times `i+1` and `i`. -/
noncomputable def dp (W : Walk n) (i : ℕ) : ℤ :=
  ((W.pre (i + 1)).pStat : ℤ) - (W.pre i).pStat

/-- The increment `Δc_i` of `c` across edge `i`. -/
noncomputable def dc (W : Walk n) (i : ℕ) : ℤ :=
  ((W.pre (i + 1)).cStat : ℤ) - (W.pre i).cStat

/-- The increment `Δv_i` of `v` across edge `i`. -/
noncomputable def dv (W : Walk n) (i : ℕ) : ℤ :=
  ((W.pre (i + 1)).vStat : ℤ) - (W.pre i).vStat

/-- Paper §4: the local defect of edge `i`,
`d_i = wt(π_i, π_{i+1}) − (Δp_i + Δc_i + Δv_i)`. -/
noncomputable def defect (W : Walk n) (i : ℕ) : ℤ :=
  (wt n (W.vert i) (W.vert (i + 1)) : ℤ) - (W.dp i + W.dc i + W.dv i)

end Walk

end Coeff2
