/-
Copyright (c) 2026 Uku Raudvere. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Uku Raudvere
-/
import Mathlib

/-!
# Words, overlap weights, proper edges (paper §2)

Formalization choices:
* The alphabet `[n] = {1,…,n}` is modelled as the natural numbers in `Finset.Icc 1 n`;
  words are raw `List ℕ`.  `0` never occurs in a valid word, so it serves as a junk
  default symbol.
* A "permutation of `[n]`" is a word with distinct symbols whose symbol set is exactly
  `{1,…,n}` (`IsPermWord`).
* `wt` is defined by the paper's displayed formula
  `wt(π,σ) = min { d : 1 ≤ d ≤ n, π_{d+1}⋯π_n = σ_1⋯σ_{n−d} }`, as a `Nat.sInf`.
  The defining set always contains `d = n` (for `n ≥ 1`), so the min is well defined
  on permutation words.
* Properness is defined by the paper's primary description (no intermediate length-`n`
  window at offset `1 ≤ h < d` is a permutation); the displayed condition (prop) is a
  statement (`properStep_iff_prop` in `Coeff2/Statements.lean`).
-/

namespace Coeff2

open List

/-- Paper §1: a *permutation of `[n]`*, as a word: distinct symbols, and the set of
symbols is exactly `[n] = {1,…,n}`.  (Hence the length is `n`.) -/
def IsPermWord (n : ℕ) (w : List ℕ) : Prop :=
  w.Nodup ∧ w.toFinset = Finset.Icc 1 n

/-- Paper §2, the edge weight: `wt(π,σ)` is the least `d` with `1 ≤ d ≤ n` and
`π_{d+1}⋯π_n = σ_1⋯σ_{n−d}`, i.e. `π.drop d = σ.take (n−d)`. -/
noncomputable def wt (n : ℕ) (u v : List ℕ) : ℕ :=
  sInf {d | 1 ≤ d ∧ d ≤ n ∧ u.drop d = v.take (n - d)}

/-- The word `π₁⋯π_n σ_{n−d+1}⋯σ_n` (`d = wt(π,σ)`) obtained by appending to `π` the
final `d` symbols of `σ` (paper §2). -/
noncomputable def overlapWord (n : ℕ) (u v : List ℕ) : List ℕ :=
  u ++ v.drop (n - wt n u v)

/-- Paper §2: the edge `π → σ` of weight `d` is *improper* if one of the intermediate
length-`n` windows of `π₁⋯π_n σ_{n−d+1}⋯σ_n`, at an offset `1 ≤ h < d`, is already a
permutation. -/
def Improper (n : ℕ) (u v : List ℕ) : Prop :=
  ∃ h, 1 ≤ h ∧ h < wt n u v ∧ IsPermWord n (((overlapWord n u v).drop h).take n)

/-- Paper §2: a *proper* edge is one that is not improper.  (Walks in the "proper
overlap graph" are chains of `ProperStep`s.) -/
def ProperStep (n : ℕ) (u v : List ℕ) : Prop :=
  ¬ Improper n u v

/-- Paper §3: the weight-1 edge out of `π = π₁π₂⋯π_n` is the cyclic rotation
`ρ(π) = π₂π₃⋯π_nπ₁`. -/
def rho (w : List ℕ) : List ℕ := w.rotate 1

/-- Paper §3: the weight-2 door out of `π`, namely `π₃π₄⋯π_nπ₂π₁`. -/
def door (w : List ℕ) : List ℕ := w.drop 2 ++ [w.getD 1 0, w.getD 0 0]

/-- Rotation (cyclic) classes of words: the quotient of `List ℕ` by the "is a cyclic
rotation of" relation (paper §3: "the cyclic classes are the orbits of this rotation").
We use one quotient type for the classes of full length-`n` words *and* for the classes
of length-`(n−1)` words that appear in marked 2-loops. -/
abbrev RotClass : Type := Quotient (List.IsRotated.setoid ℕ)

/-- The rotation class of a word. -/
def rotClass (w : List ℕ) : RotClass := Quotient.mk _ w

/-- Paper §3: a *marked 2-loop* is a pair `L = (α, K)` where `α ∈ [n]` is the marker and
`K` is a cyclic class of words using the `n−1` symbols in `[n] \ {α}`.  We use the raw
pair type (so that all dynamic definitions are total); the validity requirement is the
predicate `IsMarkedLoop`. -/
abbrev MarkedLoop : Type := ℕ × RotClass

/-- The validity condition on a marked 2-loop `(α, K)`: `α ∈ [n]`, and every
representative of `K` is a word with distinct symbols whose symbol set is exactly
`[n] \ {α}` (hence has length `n−1`). -/
def IsMarkedLoop (n : ℕ) (L : MarkedLoop) : Prop :=
  L.1 ∈ Finset.Icc 1 n ∧
    ∀ w, rotClass w = L.2 → w.Nodup ∧ w.toFinset = Finset.Icc 1 n \ {L.1}

/-- Paper §3: the vertex set of the marked 2-loop `L = (α, K)`:
`V(L) = {σ ∈ S_n : del_α(σ) ∈ K}`, where `del_α` deletes the symbol `α`.
(`List.erase` deletes the first — hence, on words with distinct symbols, the only —
occurrence.) -/
def V (n : ℕ) (L : MarkedLoop) : Set (List ℕ) :=
  {σ | IsPermWord n σ ∧ rotClass (σ.erase L.1) = L.2}

/-- Paper §3: the marked 2-loop generated by `σ = π₁⋯π_n`, namely
`(π_n, [π₁⋯π_{n−1}])`: marker the last symbol, class the rotation class of the rest.
(Written `L(σ)` in the paper.) -/
def genLoop (σ : List ℕ) : MarkedLoop :=
  (σ.getLastD 0, rotClass σ.dropLast)

end Coeff2
